Sd 66 Roster page
kkatlopez/swim.me pull request #11
Opened 2022-04-05 17:02 UTC by kkatlopez

please test on your machine!

2022-04-05 17:04 UTC, kkatlopez commented
btw, images are still not in -- not sure how we wanna do that, but i'll create a Jira issue for it

2022-04-05 18:47 UTC, matthewyoungbar requested changes
Do you want to integrate pictures with this PR?

2022-04-05 18:47 UTC, matthewyoungbar commented on client/src/components/RosterProfileLatest.js
> +            var specific_result = result.find(x => (x.meetName === this.state.latestmeet[0] && x.meetStartDate === this.state.latestmeet[1]));
If the find doesn't find anything, it returns `undefined` and crashes the app on line 40.

2022-04-05 18:47 UTC, matthewyoungbar commented on client/src/components/RosterProfileLatest.js
> +            var specific_result = result.find(x => (x.meetName === this.state.latestmeet[0] && x.meetStartDate === this.state.latestmeet[1]));
The error happened a few times for me but not for every card...

2022-04-05 22:29 UTC, kkatlopez commented on client/src/components/RosterProfileLatest.js
> +            var specific_result = result.find(x => (x.meetName === this.state.latestmeet[0] && x.meetStartDate === this.state.latestmeet[1]));
do you remember which cards?

2022-04-05 22:30 UTC, kkatlopez commented
@matthewyoungbar how did you want to store images again? were we gonna scrape them or

2022-04-06 03:49 UTC, matthewyoungbar commented
> @matthewyoungbar how did you want to store images again? were we gonna scrape them or

I thought were planning on putting them under credentials but we never fully decided

2022-04-10 19:49 UTC, kkatlopez commented on client/src/components/RosterProfileLatest.js
> +            var specific_result = result.find(x => (x.meetName === this.state.latestmeet[0] && x.meetStartDate === this.state.latestmeet[1]));
@matthewyoungbar fixed, please test

2022-04-11 04:07 UTC, gwynethyuen requested changes
- latest tab on specific swimmer page isn't scrollable
- is by event supposed to show stuff? nothing's working for me

2022-04-12 03:13 UTC, matthewyoungbar approved these changes

2022-04-12 03:13 UTC, merged