SD-62: styling for login DONE ! :D
kkatlopez/swim.me pull request #12
Opened 2022-04-10 19:13 UTC by kkatlopez

2022-04-10 19:50 UTC, matthewyoungbar requested changes

2022-04-10 19:50 UTC, matthewyoungbar commented on client/src/components/UserLogin.js
> +              <Button onClick={this.confirmCreds} className={"green-button " + (this.state.submittable ? "" : "disabled")} disabled={!this.state.submittable}>Sign in</Button>
This button is unselectable if the browser auto-fills the username and password, which is rather annoying.
It is also still unclickable on iOS (both Safari and iOS Chrome).

2022-04-10 19:52 UTC, kkatlopez commented on client/src/components/UserLogin.js
> +              <Button onClick={this.confirmCreds} className={"green-button " + (this.state.submittable ? "" : "disabled")} disabled={!this.state.submittable}>Sign in</Button>
i think were fine for the autofill thing... but not sure what to do about the unclickable on iOS, did gwyneth's branch on SD-71 fix that? it hasn't been merged to main

2022-04-10 19:56 UTC, matthewyoungbar commented on client/src/components/UserLogin.js
> +              <Button onClick={this.confirmCreds} className={"green-button " + (this.state.submittable ? "" : "disabled")} disabled={!this.state.submittable}>Sign in</Button>
No I don't think we got it to work on that branch either

2022-04-11 03:51 UTC, gwynethyuen approved these changes
we can fix the ios/touch thing in SD-71

2022-04-12 02:39 UTC, matthewyoungbar approved these changes

2022-04-12 03:05 UTC, merged